"""Update Analysis model

Revision ID: b38971189e5b
Revises: 20f820b256a9
Create Date: 2024-09-15 21:32:29.706798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38971189e5b'
down_revision: Union[str, None] = '20f820b256a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analyses_user_type', table_name='analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_analyses_user_type', 'analyses', ['user_type'], unique=False)
    # ### end Alembic commands ###
